@extends('layouts.app')

@section('content')
<!--BEGIN CONTAINER-->
<div class="container"><br>

  <!--BEGIN HEADER ROW-->
  <div class="row">
    <div class="col-lg-12 col-xs-12">
      <div class="panel panel-default noborders noshadows">
        <p class="heading center equivalence up">{{$project->title_project}} - {{$category->category_name}} Project </p><br>
        @if($parent_project)
        <p class="base center equivalence up">Parent project:
        <a href="{{asset('view-project')}}/{{$parent_project->id_project}}">{{$parent_project->title_project}}</a>
        @endif
        </p>
        <div class="row">
          <div class="col-lg-3 col-xs-12">
            @if($project->img_project!=='no-image')<img class="img-responsive"  src="{{asset('images/projects')}}/{{$project->img_project}}">
            @else
            &nbsp;
            @endif
          </div>
          <div class="col-lg-9 col-xs-12">
            <div id="project-desc">
              <p>{!!$projectDescription!!}</p>
              <p><strong>Creator: </strong><a>{{$creator->name}}</a></p>
              @if(!$coordinators->isEmpty())<p><strong>Coordinators: </strong>@foreach($coordinators as $coordinator)<a>{{$coordinator->name}},&nbsp;</a>@endforeach</p>@endif
              @if(!$experts->isEmpty())<p><strong>Experts: </strong>@foreach($experts as $expert)<a>{{$expert->name}},&nbsp;</a>@endforeach</p>@endif
              @if(!$reporters->isEmpty())<p><strong>Reporters: </strong>@foreach($reporters as $reporter)<a>{{$reporter->name}},&nbsp;</a>@endforeach</p>@endif
              <p><strong>Location: </strong><span class="care">@foreach($places as $place) {{$place['location_name']}} @endforeach</span></p>
              <p><strong>Budget: </strong>@if($project->zero_budget_project!==1)<span class="transparency">
                {{$project->budget_project}} euro</span>
                @else <span class="transparency">Zero</span>@endif</p>
                <p><strong>Hudget: </strong><span class="freedom"> {{$project->hudget_project}} people</span></p>
                <br>
              <a id="co-donate" class="btn btn-success">Co-donate</a><br><br>
            </div>
            <div id="project-vote-container">
              @include('auth.partials.new-vote-module', [
                'id_comment' => '',
                'button' => 'vote-button',
                  'color'  => [
                  '1' => '#FF9000',
                  '2' => '#FFDD00',
                  '3' => '#88DD33',
                  '4' => '#22DDEE',
                  '5' => '#4488EE',
                  '6' => '#AA66DD',
                  '7' => '#FF77CC',
                ],
                'label' => [
                  '1' => 'VOTE',
                  '2' => 'TRUST',
                  '3' => 'CARE',
                  '4' => 'JOKE',
                  '5' => 'COMMIT',
                  '6' => 'AI',
                  '7' => 'BIZARRE',
                ],
                'popover' => [
                  '1' => 'eq-popover',
                  '2' => 'trust-popover',
                  '3' => 'care-popover',
                  '4' => 'joke-popover',
                  '5' => 'commit-popover',
                  '6' => 'ai-popover',
                  '7' => 'bizarre-popover'
                ],
                'title' => [
                  '1' => 'Vote',
                  '2' => 'Trust',
                  '3' => 'Heart',
                  '4' => 'Joke',
                  '5' => 'Commitment',
                  '6' => 'A.I.',
                  '7' => 'Bizarre'
                ],
                'description' => [
                  '1' => 'Click if you like this project',
                  '2' => 'Click if you have faith in this project',
                  '3' => 'Click if you are in love with this project',
                  '4' => 'Click if you thik this comment is not so serious...',
                  '5' => 'Click if you would like to participate to this project',
                  '6' => 'This value will be automatically generated by our Artificial Intelligence',
                  '7' => 'Click if you think this project is creative or out of the box'
                ],
                'vote_button' => [
                  '1' => 'equivalence',
                  '2' => 'trust',
                  '3' => 'care',
                  '4' => 'joke',
                  '5' => 'commit',
                  '6' => 'ai',
                  '7' => 'bizarre'
                ],
                'vote_comment' => [
                  '1' => 'equivalence',
                  '2' => 'trust',
                  '3' => 'care',
                  '4' => 'joke',
                  '5' => 'commit',
                  '6' => 'ai',
                  '7' => 'bizarre'
                  ],
                'id' => [
                  '1' => 'vote-equivalence',
                  '2' => 'vote-trust',
                  '3' => 'vote-care',
                  '4' => 'vote-joke',
                  '5' => 'vote-commit',
                  '6' => 'vote-ai',
                  '7' => 'vote-bizarre'
                  ],
                'icon' => [
                  '1' => 'icon-equivalence',
                  '2' => 'icon-trust',
                  '3' => 'icon-care',
                  '4' => 'icon-joke',
                  '5' => 'icon-commit',
                  '6' => 'icon-ai',
                  '7' => 'icon-bizarre'
                  ],
                'label_id' => [
                  '1' => 'label-equivalence',
                  '2' => 'label-trust',
                  '3' => 'label-care',
                  '4' => 'label-joke',
                  '5' => 'label-commit',
                  '6' => 'label-ai',
                  '7' => 'label-bizarre'
                  ],
                'has_voted' => [
                  '1' => $voted_equivalence,
                  '2' => $voted_trust,
                  '3' => $voted_care,
                  '4' => $voted_joke,
                  '5' => $voted_commit,
                  '6' => 'null',
                  '7' => $voted_bizarre
                  ],
                'total' => [
                  '1' => $total_equivalence,
                  '2' => $total_trust,
                  '3' => $total_care,
                  '4' => $total_joke,
                  '5' => $total_commit,
                  '6' => $total_ai,
                  '7' => $total_bizarre
                  ],
                  ])
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!--END ROW-->

  <!--COMMENT SECTION LEVEL ONE-->
  <div class="row">
    <div style="height:10px;"></div>
    <div class="col-lg-2 col-xs-12"></div>
      <!--main border, better to substitute with a margin-->
    <div class="col-lg-8 col-xs-12">
      <!--COMMENT FIELD-->
      <div style="height:15px;"></div>
      <div class="row" id="comment-field">
        <div class="col-lg-12 col-xs-12">

          {!! Form::open ( array ('route' => 'new-comment', 'method' => 'post')) !!}
          <div>
            <textarea name="comment_content" rows="3" maxlength="1000" class="form-control"></textarea>
            <input type="hidden" name="user_id" value="{{Auth::user()->id}}">
            <input type="hidden" name="project_id" value="{{$project->id_project}}">
            <div class="center">
              <button type="submit" class="btn btn-default">Post!</button>
            </div>
          </div>
          {!! Form::close () !!}
          <br>
        </div>
      </div>
      <!--END COMMENT FIELD-->
      <!-- it displays "nothing yet.." if nothing happened, otherwise all the post/comments -->
      @if (empty($comments))
      <p class="base">No comments yet</p>
      @else

<!--      @foreach($comments as $comment)
        {{ $comment['id_comment']}}
      @endforeach
-->

      @foreach($comments as $comment)
        <div class="col-lg-12 col-xs-12">
          @include('auth.partials.comment-content',[
            'id_comment'  => $comment['id_comment'],
            'content'     => $comment['content']
            ])
          @include('auth.partials.comment-published',[
            'id_comment'  => $comment['id_comment'],
            'birth'       => $project->birth_project,
            'not_anonymous' => $project->not_anonymous,
            'author'      => $comment['author_name'],
            'date'        => $comment['date']
            ])
          @include('auth.partials.actions-module', [
              'id_author'   => $comment['author_id'],
              'id_comment'  => $comment['id_comment']
           ])
          @include('auth.partials.showreply-module',[
            'replies' => $comment['replies'],
            'id_comment'  => $comment['id_comment']
            ])
          @include('auth.partials.new-vote-module', [
                'id_comment' => $comment['id_comment'],
                'button' => 'vote-comment',
                'color'  => [
                  '1' => '#FF9000',
                  '2' => '#FFDD00',
                  '3' => '#88DD33',
                  '4' => '#22DDEE',
                  '5' => '#4488EE',
                  '6' => '#AA66DD',
                  '7' => '#FF77CC',
                ],
                'label' => [
                  '1' => 'VOTE',
                  '2' => 'TRUST',
                  '3' => 'CARE',
                  '4' => 'JOKE',
                  '5' => 'COMMIT',
                  '6' => 'AI',
                  '7' => 'BIZARRE',
                ],
                'popover' => [
                  '1' => 'eq-popover',
                  '2' => 'trust-popover',
                  '3' => 'care-popover',
                  '4' => 'joke-popover',
                  '5' => 'commit-popover',
                  '6' => 'ai-popover',
                  '7' => 'bizarre-popover'
                  ],
                'title' => [
                  '1' => 'Vote',
                  '2' => 'Trust',
                  '3' => 'Heart',
                  '4' => 'Joke',
                  '5' => 'Commitment',
                  '6' => 'A.I.',
                  '7' => 'Bizarre'
                  ],
                'description' => [
                  '1' => 'Click if you like this comment',
                  '2' => 'Click if you trust the author of this comment',
                  '3' => 'Click if you are in love with this comment',
                  '4' => 'Click if you thik this comment is not so serious...',
                  '5' => 'Click if you are ready to commit with this comment',
                  '6' => 'This value will be automatically generated by our Artificial Intelligence',
                  '7' => 'Click if you think this comment is smart, creative or out of the box'
                  ],
                'vote_comment' => [
                  '1' => 'equivalence',
                  '2' => 'trust',
                  '3' => 'care',
                  '4' => 'joke',
                  '5' => 'commit',
                  '6' => 'ai',
                  '7' => 'bizarre'
                  ],
                'vote_comment' => [
                  '1' => 'equivalence',
                  '2' => 'trust',
                  '3' => 'care',
                  '4' => 'joke',
                  '5' => 'commit',
                  '6' => 'ai',
                  '7' => 'bizarre'
                  ],
                'id' => [
                  '1' => 'vote-equivalence',
                  '2' => 'vote-trust',
                  '3' => 'vote-care',
                  '4' => 'vote-joke',
                  '5' => 'vote-commit',
                  '6' => 'vote-ai',
                  '7' => 'vote-bizarre'
                  ],
                'icon' => [
                  '1' => 'icon-equivalence',
                  '2' => 'icon-trust',
                  '3' => 'icon-care',
                  '4' => 'icon-joke',
                  '5' => 'icon-commit',
                  '6' => 'icon-ai',
                  '7' => 'icon-bizarre'
                  ],
                'label_id' => [
                  '1' => 'label-equivalence',
                  '2' => 'label-trust',
                  '3' => 'label-care',
                  '4' => 'label-joke',
                  '5' => 'label-commit',
                  '6' => 'label-ai',
                  '7' => 'label-bizarre'
                  ],
                'has_voted' => [
                  '1' => $comment['voted_equivalence'],
                  '2' => $comment['voted_trust'],
                  '3' => $comment['voted_care'],
                  '4' => $comment['voted_joke'],
                  '5' => $comment['voted_commit'],
                  '6' => 'null',
                  '7' => $comment['voted_bizarre']
                  ],
                'total' => [
                  '1' => $comment['vote_equivalence'],
                  '2' => $comment['vote_trust'],
                  '3' => $comment['vote_care'],
                  '4' => $comment['vote_joke'],
                  '5' => $comment['vote_commit'],
                  '6' => $comment['vote_ai'],
                  '7' => $comment['vote_bizarre']
                  ],
              ])
          @include('auth.partials.activate-popovers',[
            'id_comment'=>$comment['id_comment']
              ])
          @include('auth.partials.comment-field',[
              'id_comment'  =>  $comment['id_comment'],
              'user_id'     =>  Auth::user()->id,
              'comment_id'  =>  $comment['id_comment'],
              'project_id'  =>  $project->id_project
             ])
          @include('auth.partials.modify-field',[
            'id_comment'  =>  $comment['id_comment'],
            'content'     => $comment['editcontent'],
            'project_id'  =>  $project->id_project
              ])
        </div>


        <!--REPLIES LEVEL TWO-->
        <div id="Replies{{$comment['id_comment']}}" class="panel-collapse collapse in">
          @foreach($comment['replies'] as $reply)
            <div class="col-lg-1 col-xs-1"></div>
            <div class="col-lg-11 col-xs-11">
            @include('auth.partials.comment-content',[
              'id_comment'  => $reply['id_comment'],
              'content'     => $reply['content']
             ])
            @include('auth.partials.comment-published',[
              'id_comment'  => $reply['id_comment'],
              'birth'       => $project->birth_project,
              'not_anonymous' => $project->not_anonymous,
              'author'      => $reply['author_name'],
              'date'        => $reply['date']
             ])
            @include('auth.partials.actions-module', [
                'id_author'   => $reply['author_id'],
                'id_comment'  => $reply['id_comment']
             ])
            @include('auth.partials.showreply-module',[
               'replies' => $reply['replies'],
               'id_comment'  => $reply['id_comment']
             ])
            @include('auth.partials.new-vote-module', [
                      'id_comment' => $reply['id_comment'],
                      'button' => 'vote-comment',
                      'color'  => [
                        '1' => '#FF9000',
                        '2' => '#FFDD00',
                        '3' => '#88DD33',
                        '4' => '#22DDEE',
                        '5' => '#4488EE',
                        '6' => '#AA66DD',
                        '7' => '#FF77CC',
                      ],
                      'label' => [
                        '1' => 'VOTE',
                        '2' => 'TRUST',
                        '3' => 'CARE',
                        '4' => 'JOKE',
                        '5' => 'COMMIT',
                        '6' => 'AI',
                        '7' => 'BIZARRE',
                      ],
                      'popover' => [
                        '1' => 'eq-popover',
                        '2' => 'trust-popover',
                        '3' => 'care-popover',
                        '4' => 'joke-popover',
                        '5' => 'commit-popover',
                        '6' => 'ai-popover',
                        '7' => 'bizarre-popover'
                        ],
                      'title' => [
                        '1' => 'Vote',
                        '2' => 'Trust',
                        '3' => 'Heart',
                        '4' => 'Joke',
                        '5' => 'Commitment',
                        '6' => 'A.I.',
                        '7' => 'Bizarre'
                        ],
                      'description' => [
                        '1' => 'Click if you like this comment',
                        '2' => 'Click if you trust the author of this comment',
                        '3' => 'Click if you are in love with this comment',
                        '4' => 'Click if you thik this comment is not so serious...',
                        '5' => 'Click if you are ready to commit with this comment',
                        '6' => 'This value will be automatically generated by our Artificial Intelligence',
                        '7' => 'Click if you think this comment is smart, creative or out of the box'
                        ],
                      'vote_comment' => [
                        '1' => 'equivalence',
                        '2' => 'trust',
                        '3' => 'care',
                        '4' => 'joke',
                        '5' => 'commit',
                        '6' => 'ai',
                        '7' => 'bizarre'
                        ],
                      'vote_comment' => [
                        '1' => 'equivalence',
                        '2' => 'trust',
                        '3' => 'care',
                        '4' => 'joke',
                        '5' => 'commit',
                        '6' => 'ai',
                        '7' => 'bizarre'
                        ],
                      'id' => [
                        '1' => 'vote-equivalence',
                        '2' => 'vote-trust',
                        '3' => 'vote-care',
                        '4' => 'vote-joke',
                        '5' => 'vote-commit',
                        '6' => 'vote-ai',
                        '7' => 'vote-bizarre'
                        ],
                      'icon' => [
                        '1' => 'icon-equivalence',
                        '2' => 'icon-trust',
                        '3' => 'icon-care',
                        '4' => 'icon-joke',
                        '5' => 'icon-commit',
                        '6' => 'icon-ai',
                        '7' => 'icon-bizarre'
                        ],
                      'label_id' => [
                        '1' => 'label-equivalence',
                        '2' => 'label-trust',
                        '3' => 'label-care',
                        '4' => 'label-joke',
                        '5' => 'label-commit',
                        '6' => 'label-ai',
                        '7' => 'label-bizarre'
                        ],
                      'has_voted' => [
                        '1' => $reply['voted_equivalence'],
                        '2' => $reply['voted_trust'],
                        '3' => $reply['voted_care'],
                        '4' => $reply['voted_joke'],
                        '5' => $reply['voted_commit'],
                        '6' => 'null',
                        '7' => $reply['voted_bizarre']
                        ],
                      'total' => [
                        '1' => $reply['vote_equivalence'],
                        '2' => $reply['vote_trust'],
                        '3' => $reply['vote_care'],
                        '4' => $reply['vote_joke'],
                        '5' => $reply['vote_commit'],
                        '6' => $reply['vote_ai'],
                        '7' => $reply['vote_bizarre']
                        ],
                        ])
            @include('auth.partials.activate-popovers', [
              'id_comment'=>$reply['id_comment']
             ])
            @include('auth.partials.comment-field',[
                  'id_comment'  =>  $reply['id_comment'],
                  'user_id'     =>  Auth::user()->id,
                  'comment_id'  =>  $reply['id_comment'],
                  'project_id'  =>  $project->id_project
                ])
            @include('auth.partials.modify-field',[
                  'id_comment'  =>  $reply['id_comment'],
                  'content'     => $reply['editcontent'],
                  'project_id'  =>  $project->id_project
                ])
            </div>
          <!--RE-REPLIES LEVEL THREE-->
          <div id="Replies{{$reply['id_comment']}}" class="panel-collapse collapse in">
            @foreach($reply['replies'] as $re_reply)
              <div class="col-lg-2 col-xs-2"></div>
              <div class="col-lg-10 col-xs-10">
              @include('auth.partials.comment-content',[
                'id_comment'  => $re_reply['id_comment'],
                'content'     => $re_reply['content']
               ])
              @include('auth.partials.comment-published',[
                'id_comment'  => $re_reply['id_comment'],
                'birth'       => $project->birth_project,
                'not_anonymous' => $project->not_anonymous,
                'author'      => $re_reply['author_name'],
                'date'        => $re_reply['date']
               ])
              @include('auth.partials.actions-module', [
                  'id_author'   => $re_reply['author_id'],
                  'id_comment'  => $re_reply['id_comment']
               ])
              @include('auth.partials.new-vote-module', [
                    'id_comment' => $re_reply['id_comment'],
                    'button' => 'vote-comment',
                    'color'  => [
                        '1' => '#FF9000',
                        '2' => '#FFDD00',
                        '3' => '#88DD33',
                        '4' => '#22DDEE',
                        '5' => '#4488EE',
                        '6' => '#AA66DD',
                        '7' => '#FF77CC',
                      ],
                      'label' => [
                        '1' => 'VOTE',
                        '2' => 'TRUST',
                        '3' => 'CARE',
                        '4' => 'JOKE',
                        '5' => 'COMMIT',
                        '6' => 'AI',
                        '7' => 'BIZARRE',
                      ],
                    'popover' => [
                      '1' => 'eq-popover',
                      '2' => 'trust-popover',
                      '3' => 'care-popover',
                      '4' => 'joke-popover',
                      '5' => 'commit-popover',
                      '6' => 'ai-popover',
                      '7' => 'bizarre-popover'
                      ],
                    'title' => [
                      '1' => 'Vote',
                      '2' => 'Trust',
                      '3' => 'Heart',
                      '4' => 'Joke',
                      '5' => 'Commitment',
                      '6' => 'A.I.',
                      '7' => 'Bizarre'
                      ],
                    'description' => [
                      '1' => 'Click if you like this comment',
                      '2' => 'Click if you trust the author of this comment',
                      '3' => 'Click if you are in love with this comment',
                      '4' => 'Click if you thik this comment is not so serious...',
                      '5' => 'Click if you are ready to commit with this comment',
                      '6' => 'This value will be automatically generated by our Artificial Intelligence',
                      '7' => 'Click if you think this comment is smart, creative or out of the box'
                      ],
                    'vote_comment' => [
                      '1' => 'equivalence',
                      '2' => 'trust',
                      '3' => 'care',
                      '4' => 'joke',
                      '5' => 'commit',
                      '6' => 'ai',
                      '7' => 'bizarre'
                      ],
                    'vote_comment' => [
                      '1' => 'equivalence',
                      '2' => 'trust',
                      '3' => 'care',
                      '4' => 'joke',
                      '5' => 'commit',
                      '6' => 'ai',
                      '7' => 'bizarre'
                      ],
                    'id' => [
                      '1' => 'vote-equivalence',
                      '2' => 'vote-trust',
                      '3' => 'vote-care',
                      '4' => 'vote-joke',
                      '5' => 'vote-commit',
                      '6' => 'vote-ai',
                      '7' => 'vote-bizarre'
                      ],
                    'icon' => [
                      '1' => 'icon-equivalence',
                      '2' => 'icon-trust',
                      '3' => 'icon-care',
                      '4' => 'icon-joke',
                      '5' => 'icon-commit',
                      '6' => 'icon-ai',
                      '7' => 'icon-bizarre'
                      ],
                    'label_id' => [
                      '1' => 'label-equivalence',
                      '2' => 'label-trust',
                      '3' => 'label-care',
                      '4' => 'label-joke',
                      '5' => 'label-commit',
                      '6' => 'label-ai',
                      '7' => 'label-bizarre'
                      ],
                    'has_voted' => [
                      '1' => $re_reply['voted_equivalence'],
                      '2' => $re_reply['voted_trust'],
                      '3' => $re_reply['voted_care'],
                      '4' => $re_reply['voted_joke'],
                      '5' => $re_reply['voted_commit'],
                      '6' => 'null',
                      '7' => $re_reply['voted_bizarre']
                      ],
                    'total' => [
                      '1' => $re_reply['vote_equivalence'],
                      '2' => $re_reply['vote_trust'],
                      '3' => $re_reply['vote_care'],
                      '4' => $re_reply['vote_joke'],
                      '5' => $re_reply['vote_commit'],
                      '6' => $re_reply['vote_ai'],
                      '7' => $re_reply['vote_bizarre']
                      ],
                   ])
              @include('auth.partials.activate-popovers', [
                'id_comment'=>$re_reply['id_comment']
                ])
              @include('auth.partials.comment-field',[
                  'id_comment'  =>  $re_reply['id_comment'],
                  'user_id'     =>  Auth::user()->id,
                  'comment_id'  =>  $reply['id_comment'],
                  'project_id'  =>  $project->id_project
               ])
              @include('auth.partials.modify-field',[
                'id_comment'  =>  $re_reply['id_comment'],
                'content'     => $re_reply['editcontent'],
                'project_id'  =>  $project->id_project
               ])
              </div>
            @endforeach
          </div>
          @endforeach
        </div>
      @endforeach
      @endif
    </div>
    <div class="col-lg-2 col-xs-12"></div>
      <!--END COMMENTS SECTION-->
      <input id="userID" type="hidden" value="{{Auth::user()->id}}">
      <input id="projectID" type="hidden" value="{{$project->id_project}}">
  </div>
  <br>
</div>
    <!--END CONTAINER-->

<!-- Modal -->
<div id="confirmDelete" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Delete comment</h4>
      </div>
      <div class="modal-body">
        <p>Are you sure? You cannot undo the operation.</p>
      </div>
      <div class="modal-footer">

        {!! Form::open ( array ('route' => 'delete-comment', 'method' => 'post')) !!}
        <input id="deleteCommentID" type="hidden" name="comment_id" value="">
        <input id="deleteCommentPID" type="hidden" name="project_id" value="{{$project->id_project}}">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-danger">Delete</button>
        {!! Form::close() !!}
      </div>
    </div>

  </div>
</div>
@endsection
