@extends('layouts.default')
@section('title')
    Equivalence - Cooperacy
@stop
@section('content')

<div id="main" class="site-main clr">


  <div id="content-wrap" class="container clr full-screen">
    <section id="primary" class="content-area clr">
      <div id="content" class="clr site-content" role="main">
        <article class="clr">
          <div class="entry-content entry clr">
            <p><img src="{{asset('images/equivalence.png')}}" width="100%" /></p>
            <div id="coomain">
              <p style="color:#FF9900; font-size: 20px; font-weight:700; margin-bottom:10px;">A DIVERSITY BASED COOPERATIVE ECONOMY</p>
              <p style="color:#FF9900; font-size: 16px; font-weight:700; margin-bottom:20px">WHERE EVERY IDENTITY IS RESPECTED</p>
              <p style="color: #555555; font-size: 16px; text-align: justify;">The idea behind a diversity-based cooperative society is that wealth is redistributed in order to let every identity have the possibility to fulfill its potentials. This idea has been the base of democracies, communist and socialist systems, and capitalist-liberal ones. Capitalism accuses communism and socialism to be fake and to destroy individual dignity. Socialism and communism instead point out that capitalism is greedy and the system brings to inequivalence. And they&#8217;re both right.</p>
              <p style="color:#FF9900; font-size: 20px; font-weight:700; margin-bottom:10px;">COMMUNISM IS BORING, CAPITALISM IS MEAN</p>
              <p style="color:#FF9900; font-size: 16px; font-weight:700; margin-bottom:20px;">OVERCOMING ALL THE ISMS</p>
              <p style="color: #555555; font-size: 16px; text-align: justify;">Riane Eisler used to say we should leave behind all the -isms. Communism didn&#8217;t work, as its homologation power negated the single identities. Socialism was too centralized to give reliability and transparency. Capitalism, instead, automatically triggers an accumulation of the resources -or financial power. Even Scandinavian countries, an example of very good &#8220;Sociocapitalism&#8221;, have difficulties in reaching a good wealth distribution. The welcomed Sharing Economy phenomenon became a form of Sharing Business in some cases, in some other a form of shared exploitation. The astounding work of Nobel Prize Elinor Ostrom about &#8220;the Commons&#8221; demonstrated decentralized power is better than centralized one. Nevertheless, having a society based on the commons still strives to be.. &#8220;common&#8221; and well distributed all over the world.</p>
              <p style="color:#FF9900; font-size: 20px; font-weight:700; margin-bottom:10px;">DON&#8217;T LOOK FOR IDEOLOGY, LOOK FOR METHODOLOGY</p>
              <p style="color:#FF9900; font-size: 16px; font-weight:700; margin-bottom:20px;">EVER HEARD ABOUT SOCIAL TECHNOLOGY?</p>
              <p style="color: #555555; font-size: 16px; text-align: justify;">Cooperation and cooperative economy have always been practiced: the US countryside power distribution system wouldn&#8217;t have ever existed without the electric cooperatives, Canadian cooperative movement was at the base of the New Democratic Party, the Gung-ho in China and the JCCU in Japan managed to survive through wars and politically adverse times, and theorists of cooperation were part of the economic-political European culture since the worker-cooperative movement started in England. Besides this, cooperative economy and the commons are rooted in African traditional culture. So.. what&#8217;s new?</p>
              <p>The new is that the study of collective intelligence, neuroeconomics and ancient African social technologies like the Open Space Technology and the Indaba, together with Ostrom&#8217;s insights on the commons, can be marged. Cooperative economy may avoid centralization and focus on methodology, like in an e-democratic cooperative crowd-equity funding, that we call <span style="color:#FF9900; font-size: 16px">Co-banking,</span> or in the concept of the <span style="color:#FF9900; font-size: 16px">Twin Systems</span>, or in our <span style="color:#FF9900; font-size: 16px">Cooperative Production</span> proposal.</p>
              <p style="color:#FF9900; font-size: 20px; font-weight:700; margin-bottom:10px;">THE TWIN SYSTEMS</p>
              <p style="color:#FF9900; font-size: 16px; font-weight:700; margin-bottom:20px;">PLAY SAFE EVERYDAY, STAY CREATIVE WHEN YOU NEED IT</p>
              <p style="color: #555555; font-size: 16px; text-align: justify;">Current economy is based on hazardous dynamics. Like in poker, you bet your work and money on the cards you have: they could be your current job, your skills, a new startup idea or a capital you want to invest. Will you get the outcomes of what you bet? Apparently, today everything is unpredictable, and nobody is sure about what will be happening to his bet. We have a system that is risky and that keeps everybody, rich and poor ones, under the threat of losing what they have. <span style="color:#FF9900; font-size: 16px">Cooperative Production</span> would avoid this, and our <span style="color:#FF9900; font-size: 16px">Co-banking</span> system can enable a change in the medium-long term, but should we base our economies only on a safe and mutual system?</p>
              <p>As long as we respect and desire diversity, we shouldn&#8217;t change the current system. Having two Twin Systems can allow people to keep things safe and well-distributed, generate a stable and base income for everybody, and provide a common and mutual growth. On the other side it would allow us to participate in the game of competition on a side market, in order to &#8220;have more&#8221; or to play into a more elastic and risk-based economy.<br />
                The current international economy is based only on the latter. Join us and let&#8217;s create together a space for a parallel market based on <span style="color:#FF9900; font-size: 16px">Co-banking</span> and <span style="color:#FF9900; font-size: 16px">Cooperative Production</span>.</p>
              <p style="color:#FF9000; font-size: 20px; font-weight:700; margin-bottom:10px;">EQUIVALENCE</p>
              <p style="color:#FF9000; font-size: 16px; font-weight:700; margin-bottom:20px;">Cooperation is different than altruism</p>
              <p style="color: #555555; font-size: 16px; font-weight:400;">Cooperation is different from altruism, solidarity and donation where we see a &#8220;recipient&#8221; that simply &#8220;receives&#8221; in a one-way action. But it is also different from compromise, do-ut-des, psychological collusion, conflictual collaboration: a feeling of mutual happiness and satisfaction is a signal of a real cooperation. <br />
                If you follow only your personal happiness, you are in the world of egoism, fraud, usury, ruthless or unfair competition. On the contrary, sometimes you are only focused on giving and you forget about yourself: we slide from concepts like altruism, donation or instinctual help till to personal sacrifice or even complete annihilation for the sake of others. What we look for is a &#8220;win-win&#8221; dynamic that is not based on the mere advantageous results, but on the happiness derived by the act of doing something together.<br />
                That&#8217;s why we talk about enjoyment. You enjoy food, a new car, and also a good friendship. We found out there are two main equivalences to be respected: an equivalence of benefit, that happens when you get as much as the other participants, and an equivalence of feelings, or equivalence of the relationship, in which you are as much happy as the other participants are.<br />
                It&#8217;s interesting to notice that for many &#8220;rationalists&#8221; and &#8220;instrumentalists&#8221; no human can make a real act of altruism: there&#8217;s always some pleasure or gain for the altruist. In the idea of a &#8220;mechanistic&#8221; perspective the dynamic seem to be correct, but something is not working with the example of the fireman -in which &#8220;rationally&#8221; the risk overcomes the benefit- and that of an adult suddendly saving a falling baby led by instinct. Moreover, latest neurological discoveries see altruism as a natural and unavoidable tendency in sound human individuals which have no altered states of consciousness.</p>
              <p style="background-color:#FF9000; color:#FFFFFF; font-size: 16px; font-weight:300; margin-bottom:0px; padding:20px;">TO SOLVE A CONFLICT WITH THE EQUIVALENCE CONDITION:<br />
                Allow experimentation and use turns so that different proposed solutions have the same importance.</p>
              <p style="color:#FF9000; font-size: 16px; font-weight:300; padding:20px;">KEY EQUIVALENCE PRACTICES<br />Adequate real and relational benefits for all participants.<br />Mutual goals, mutual motivations. Direct, indirect, group and network reciprocity.</p>
              <p style="color: #555555; font-size: 16px; font-weight:400;">
                Mutual satisfaction or happiness is one of the most important concepts which derives from adequate relational and real benefits for every paticipant. We can also list indirect environmental factors that may raise that condition: beauty of location and objects, personal care of participants and a pleasant presence in sounds, tastes, smells, and surfaces may lead everybody to feel satisfied, happy and enjoy the common action. A good climate is very important also in the team building perspective, and scholars have dedicated great efforts with interdisciplinary studies about game and humour effects, indicating that those factors can develop a good climate, team spirit and mutual happiness, overall in neutral collaboration with collective enjoyment.</p>
              <p>A mutual goal magnifies cooperation conditions, because all individual efforts converge, raising benefits and usually -when a collaboration is not a collusion or a compromise- generating more satisfaction. Moreover, the possibility of identification and belonging is stronger so relationships tend to be more intense. But remember: <em>diversity is always there and &#8220;your&#8221; idea of the goal wouldn&#8217;t ever be exactly the same as the other participants one</em>.<br />
                Motivation is different than goal. You may think about it as a &#8220;meta-goal&#8221;, the &#8220;goal&#8221; you pursue a goal for. When motivation is mutual, like above, it booss cooperation. The Non-Violent Communication focuses on needs, that could be interpreted as motivations. Those needs are quite universal and many people can agree on them. Remember: <em>it is way easier to agree on a motivation, a need, a value rather than a very specific goal.</em>Nevertheless, once agreed on the motivation, you should talk about what to do in the specific.<br />
                In behavioural statistic studies, it has been demonstrated that instrumental interests in the search for cooperation can&#8217;t avoid similar social motivation and that the instrumental component has lower efficacy compared to social motivation and group identification. Again, benefits drive, but feelings drive most.</p>
              <p>Since the first studies on the &#8220;Tit for Tat&#8221; strategy and from an analytical point of view, &#8220;reciprocity&#8221; is able to generate a trend of choices that has as effect adequate benefits in participants. &#8220;Mutuality&#8221;, a reciprocity in which the exchange or balance of benefits isn&#8217;t the main purpose of the interaction like in &#8220;do-ut-des&#8221; mechanisms, is to be preferred, as it integrates a reciprocation of motivations and feelings together with the mere real benefits. In the &#8220;mutuality&#8221; term there&#8217;s some sort of reciprocal help too, while &#8220;reciprocity&#8221; in game theory would also include retaliation, an attitude that has been demonstrated -together with punishment- not as much as effective as social motivation, non-violent communication, good relationship. Motivation and identity with the group are stronger and more valid boosters. Respect of every identity in particular merges the feeling of the self with the others and the group identity itself.</p>
            </div>
          </div><!-- .entry-content -->
        </article><!-- #post -->
      </div><!-- #content -->
    </section><!-- #primary -->
  </div><!-- #content-wrap -->


</div><!-- #main -->

@stop
