@include('auth.partials.new-vote-module', [
  'id_comment' => $project['id_project'],
  'button' => 'vote-button',
  'color'  => [
    '1' => '#FF9000',
    '2' => '#FFDD00',
    '3' => '#88DD33',
    '4' => '#22DDEE',
    '5' => '#4488EE',
    '6' => '#AA66DD',
    '7' => '#FF77CC',
  ],
    'label' => [
      '1' => 'VOTE',
      '2' => 'TRUST',
      '3' => 'CARE',
      '4' => 'JOKE',
      '5' => 'COMMIT',
      '6' => 'AI',
      '7' => 'BIZARRE',
  ],
  'popover' => [
    '1' => 'eq-popover',
    '2' => 'trust-popover',
    '3' => 'care-popover',
    '4' => 'joke-popover',
    '5' => 'commit-popover',
    '6' => 'ai-popover',
    '7' => 'bizarre-popover'
    ],
  'title' => [
    '1' => 'Vote',
    '2' => 'Trust',
    '3' => 'Heart',
    '4' => 'Joke',
    '5' => 'Commitment',
    '6' => 'A.I.',
    '7' => 'Bizarre'
    ],
  'description' => [
    '1' => 'Click if you like this project',
    '2' => 'Click if you have faith in this project',
    '3' => 'Click if you are in love with this project',
    '4' => 'Click if you thik this comment is not so serious...',
    '5' => 'Click if you would like to participate to this project',
    '6' => 'This value will be automatically generated by our Artificial Intelligence',
    '7' => 'Click if you think this project is creative or out of the box'
    ],
  'vote_button' => [
    '1' => 'equivalence',
    '2' => 'trust',
    '3' => 'care',
    '4' => 'joke',
    '5' => 'commit',
    '6' => 'ai',
    '7' => 'bizarre'
    ],
  'vote_comment' => [
    '1' => 'equivalence',
    '2' => 'trust',
    '3' => 'care',
    '4' => 'joke',
    '5' => 'commit',
    '6' => 'ai',
    '7' => 'bizarre'
    ],
  'id' => [
    '1' => 'vote-equivalence+'.$project['id_project'],
    '2' => 'vote-trust+'.$project['id_project'],
    '3' => 'vote-care+'.$project['id_project'],
    '4' => 'vote-joke+'.$project['id_project'],
    '5' => 'vote-commit+'.$project['id_project'],
    '6' => 'vote-ai+'.$project['id_project'],
    '7' => 'vote-bizarre+'.$project['id_project']
    ],
  'icon' => [
    '1' => 'icon-equivalence',
    '2' => 'icon-trust',
    '3' => 'icon-care',
    '4' => 'icon-joke',
    '5' => 'icon-commit',
    '6' => 'icon-ai',
    '7' => 'icon-bizarre'
    ],
  'label_id' => [
    '1' => 'label-equivalence-',
    '2' => 'label-trust-',
    '3' => 'label-care-',
    '4' => 'label-joke-',
    '5' => 'label-commit-',
    '6' => 'label-ai-',
    '7' => 'label-bizarre-'
    ],
  'has_voted' => [
    '1' => $project['voted_equivalence'],
    '2' => $project['voted_trust'],
    '3' => $project['voted_care'],
    '4' => $project['voted_joke'],
    '5' => $project['voted_commit'],
    '6' => 'null',
    '7' => $project['voted_bizarre']
    ],
  'total' => [
    '1' => $project['total_equivalence'],
    '2' => $project['total_trust'],
    '3' => $project['total_care'],
    '4' => $project['total_joke'],
    '5' => $project['total_commit'],
    '6' => $project['total_ai'],
    '7' => $project['total_bizarre']
    ],
  ])
