@extends('layouts.lvapp')
@section('title')
    About Us - Cooperacy
@stop
@section('content')

<!--BEGIN CONTAINER-->
<div class="containerone">

  <!--BEGIN HEADER-->
  <div class="row">
    <br><img class="page-header" src="{{asset('/images/aboutus.png')}}">
  </div>
  <!--END HEADER-->

  <!--BEGIN ROW-->
  <div class="row">

  <!--BEGIN LEFT COL-->
  <div class="col-md-2"></div>
  <!--END LEFT COL-->

    <!-- journey anytime you will feel lost you can summon a mentor to guide you -->

  <!--BEGIN CONTENT-->
  <div class="col-md-8"><br>
  <p class="base">Cooperacy is a nonprofit project aiming to support our social ecosystem fostering the enjoyment of cooperation: on a more technical side, this is achieved transforming the current <a class="au" href="https://en.wikipedia.org/wiki/Pareto_distribution">power law</a> distribution of resources, decisions and activities into a more even one.<br><br>

  The <a class="ai" href="/platform">Cooperacy Platform</a> is the base of Cooperacy circular economic ecosystem. The participants voluntarily pool one euro per month into a common sum in order to fund their own ideas. The profits generated by these ideas goes back to the common pool. This triggers a co-owned virtuous process.

  To fund itself, Cooperacy offers also parallel services and activities: <a class="ai" href="/overview">Cooperacy Overview</a> is a measurement of the cooperation amount in larger organizations or institutions in order to promote their resilient growth. For example, the <a class="ai" href="/cci">Cooperation Context Index</a> shows the possibility of cooperation in most of the countries in the world.<br><br>
  <a class="ai" href="/openecosystem">Cooperacy Experience</a> is the live application of the Cooperacy model. The participants of any organization or community can enjoy a natural social system able to generate collaboration, innovation and problem solving.<br><br>
  <a class="ai" href="/science">Cooperacy Research</a> is instead a continuous scientific investigation about possible social systems based on cooperation and ecosystemic awareness.<br><br>

  <p class="base">If you consider our society and its natural ecosystem as a whole living organism, being part of Cooperacy means supporting this organism with the enjoyment of cooperation. <a class="ae" href="/join">Joining</p> the voluntary pool will let you experiment and support a different social ecosystem based on cooperation and common enjoyment.</p><br><br>

  </div>
  <!--END CONTENT-->

  <!--BEGIN RIGHT COL-->
  <div class="col-md-2"></div>
  <!--END RIGHT COL-->

  </div>
  <!--END ROW-->

  <!--BEGIN ROW-->
  <div class="row">

  <!--BEGIN LEFT COL-->
  <div class="col-md-2"></div>
  <!--END LEFT COL-->

  <!--BEGIN CONTENT-->
  <div class="col-md-8">


  <br><br><p class="subheading transparency center space">THE TEAM</p><br><br>

  <style>table, tbody, tr {border=0 !important; border-collapse: collapse; border-style: hidden !important;}
        td {border=0 !important; width: 12%;border-collapse: collapse; border-style: hidden !important;}
  </style>

  <div class="row">
    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 text-center">
      <img class="img-responsive" style="margin:0 auto;" src="{{asset('images/amdp.png')}}" alt="null" /><br>
      <p>Alessandro Merletti De Palo<br><i>Co-founder and coordinator of Cooperacy</i></p>
    </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 text-center">
      <img class="img-responsive" style="margin:0 auto;" src="{{asset('images/ilario.png')}}" alt="null" /><br>
     <p>Ilario Tito<br><i>Co-founder</i></p>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 text-center">
  <img class="img-responsive" style="margin:0 auto;" src="{{asset('images/beatrice.png')}}" alt="null" /><br>
 <p>Beatrice Carli Moretti<br><i>Communication Coordinator</i></p>
</div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 text-center">
      <img class="img-responsive" style="margin:0 auto;" src="{{asset('images/curti.png')}}" alt="null" /><br>
      <p>Ilaria Curti<br><i>Marketing Coordinator</i></p>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 text-center">
      <img class="img-responsive" style="margin:0 auto;" src="{{asset('images/marco.png')}}" alt="null" /><br>
      <p>Marco Marincola<br><i>Finance</i></p>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 text-center">
          <img class="img-responsive" style="margin:0 auto;" src="{{asset('images/giosetta.png')}}" alt="null" /><br>
          <p>Giosetta Ciuffa<br><i>External Relations</i></p>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 text-center">
      <img class="img-responsive" style="margin:0 auto;" src="{{asset('images/sara.png')}}" alt="null" /><br>
      <p>Sara Conallo<br><i>Jackie of all trades</i></p>
    </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 text-center">
      <img class="img-responsive" style="margin:0 auto;" src="{{asset('images/framba.png')}}" alt="null" /><br>
      <p>Federica Framba<br><i>Art Director</i></p>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 text-center">
      <img class="img-responsive" style="margin:0 auto;" src="{{asset('images/enea.png')}}" alt="null" /><br>
      <p>Enea Barbetta<br><i>Main Developer</i></p>
    </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 text-center">
      <img class="img-responsive" style="margin:0 auto;" src="{{asset('images/valentina.png')}}" alt="null" /><br>
     <p>Valentina Panizza<br><i>Strategic Planning</i></p>
    </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 text-center">
      <img class="img-responsive" style="margin:0 auto;" src="{{asset('images/stefania.png')}}" alt="null" /><br>
      <p>Stefania Forlani<br><i>Planning Updates</i></p>
    </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 text-center">
      <img class="img-responsive" style="margin:0 auto;" src="{{asset('images/francesco.png')}}" alt="null" /><br>
      <p>Francesco Taskayali<br><i>First Pianist</i></p>
    </div>
  </div>

  <!--<div class="row">
    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 text-center">
      <img class="img-responsive" style="margin:0 auto;" src="{{asset('images/giovanna.png')}}" alt="null" /><br>
      <p>Giovanna Littardi<br><i>First Guitarist</i></p>
    </div> -->

    </div>
  </div><br><br>

  <!--END CONTENT-->

  <!--BEGIN ROW-->
  <div class="row">

  <!--BEGIN LEFT COL-->
  <div class="col-md-2"></div>
  <!--END LEFT COL-->

  <!--BEGIN CONTENT-->
  <div class="col-md-8"><br>

  <p class="subheading transparency center space">FINANCE</p><br>
  <p class="base">We like so much transparency that we want everyone to be able to know our bank account balance and inspect our paypal account. We have nothing to hide.<br>
  <span class="transparency up">Bank account:</span> our IBAN is IT61D0623001623000043225634 - Filiale AG 23 Milano Cariparma di via della Moscova, and the current bank balance is around 200 euros, updated: 14 April 2018<br />
  <span class="transparency up">Paypal:</span> you can access our account from the standard paypal login with COOPERATION + password cooperation2016</p><br>

  <p class="subheading transparency center space">LEGAL STUFF</p><br>
  <p class="base">The Cooperacy Association was founded in Italy, Milan, the day 21/07/2015. Its current address is Via della Moscova 39, 20121 Milano.</p><br>

  <p id="contributors" name="contributors" style="color: #22DDEE; font-size: 24px; font-weight: bold; margin-bottom: 10px;">

  <p class="subheading transparency center space">CONTRIBUTORS LIST AND PLANNING</p><br>
  <p class="base">You can see in our <a class="ai" href="https://goo.gl/OYcrOS">planning</a> the list of names as well as the relative monetary value of the activity (including expenses) done as if monetary wages would have been corresponded to the participants. We keep track about it as we would correspond those amounts if we will have the possibility.<br><br>

  We're still doing some more work to allow better transparency. If you don't see something you're curious of, please <a class="ai" href="/contact">ask</a> for more information to be shown in this page.<br>
  Moreover, if you want, have a look at what could be <a class="ac" href="/aboutyou">your</a> interest in Cooperacy.</p>

  </div>
  <!--END CONTENT-->

  <!--BEGIN RIGHT COL-->
  <div class="col-md-2"></div>
  <!--END RIGHT COL-->

  </div>
  <!--END ROW-->

  <!--BEGIN SPACER-->
  <div class="row"><p style="height:20px;"></p></div>
  <!--END SPACER-->

</div>
<!--END CONTAINER-->


@stop
