@extends('layouts.lvapp')
@section('title')
    About Us - Cooperacy
@stop
@section('content')

<!--BEGIN CONTAINER-->
<div class="containerone">

  <!--BEGIN HEADER-->
  <div class="row">
    <br><img class="page-header" src="{{asset('/images/aboutus.png')}}">
  </div>
  <!--END HEADER-->

  <!--BEGIN ROW-->
  <div class="row">

  <!--BEGIN LEFT COL-->
  <div class="col-md-2"></div>
  <!--END LEFT COL-->

    <!-- journey anytime you will feel lost you can summon a mentor to guide you -->

  <!--BEGIN CONTENT-->
  <div class="col-md-8"><br>
  <p class="base">Cooperacy is a scientific project that through research, applications and narratives supports the social and the natural ecosystems with the energy of cooperation. The main point in cooperation is to generate mutual enjoyment: this is achieved changing the <a class="au" href="https://en.wikipedia.org/wiki/Power_law">power law</a> distribution of resources, decisions and activities into a more even distribution.<br><br>

  In the specific, the <a class="ai" href="/platform">Cooperacy Platform</a> is a worldwide scale experiment willing to create a social ecosystem based on distribution of wealth, activities and <a class="ai" href="/platform">governance</a>. The participants mutually collect one euro per month into a common sum in order to fund their own ideas. The profit generated by these ideas goes back to the collective money. This triggers a co-owned redistributive process able to generate a parallel, circular economic ecosystem. We are currently setting up the platform thanks to the current members effort, feel free to learn <a class="ai" href="/platform">more</a> and <a class="ae" href="/login">help</a> us out.<br><br>

  <a class="ai" href="/overview">Cooperacy Overview</a> is an evaluation of the cooperation conditions amongst larger organizations or institutions in order to understand their complexity, maintain their balance and promote their resilient growth through focused interventions. A public output of Cooperacy Overview is the <a class="ai" href="/cci">Cooperation Context Index</a>, which shows the possibility of cooperation in most of the countries in the world.<br><br>

  <a class="ai" href="/openecosystem">Cooperacy Experience</a> is the live application of the Cooperacy model made for groups, companies and institutions. The participants can enjoy a natural organization able to generate collaboration, innovation and problem solving. Experiencing cooperation in a live event makes it easy to understand its value on a larger scale.<br><br>

  <a class="ai" href="/science">Cooperacy Research</a> is instead the main core level, investigating a social ecosystem model based on cooperation science and aiming to spread cooperation and ecosystemic awareness through traditional and learning-by-doing education.<br><br>

  <p class="base">If you consider our society as an ecosystem, cooperation is what makes this ecosystem alive. Thinking in terms of ecosystems gives you the ability to connect the different parts of our society and of our natural world together, like a whole living organism. Being part of Cooperacy means supporting this organism with the enjoyment of cooperation.</p>

  <p class="base">The single euro per month membership fee goes in the common <a class="ai" href="/platform">Cooperacy Platform</a> collected money for you to experiment or support the cooperation-based social ecosystem and have access to our live webinars. If you believe in cooperation, join our group and start <a class="ae" href="/participate">participating</a> now!</p><br><br>

  </div>
  <!--END CONTENT-->

  <!--BEGIN RIGHT COL-->
  <div class="col-md-2"></div>
  <!--END RIGHT COL-->

  </div>
  <!--END ROW-->

  <!--BEGIN ROW-->
  <div class="row">

  <!--BEGIN LEFT COL-->
  <div class="col-md-2"></div>
  <!--END LEFT COL-->

  <!--BEGIN CONTENT-->
  <div class="col-md-8">


  <br><br><p class="subheading transparency center space">THE TEAM</p><br><br>

  <style>table, tbody, tr {border=0 !important; border-collapse: collapse; border-style: hidden !important;}
        td {border=0 !important; width: 12%;border-collapse: collapse; border-style: hidden !important;}
  </style>

  <div class="row">
    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 text-center">
      <img class="img-responsive" style="margin:0 auto;" src="{{asset('images/amdp.png')}}" alt="null" /><br>
      <p>Alessandro Merletti De Palo<br><i>Founder and Co-President of Cooperacy</i></p>
    </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 text-center">
      <img class="img-responsive" style="margin:0 auto;" src="{{asset('images/ilario.png')}}" alt="null" /><br>
     <p>Ilario Tito<br><i>Co-President and Co-Founder</i></p>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 text-center">
  <img class="img-responsive" style="margin:0 auto;" src="{{asset('images/beatrice.png')}}" alt="null" /><br>
 <p>Beatrice Carli Moretti<br><i>Communication Coordinator</i></p>
</div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 text-center">
      <img class="img-responsive" style="margin:0 auto;" src="{{asset('images/curti.png')}}" alt="null" /><br>
      <p>Ilaria Curti<br><i>Marketing and Communication</i></p>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 text-center">
      <img class="img-responsive" style="margin:0 auto;" src="{{asset('images/marco.png')}}" alt="null" /><br>
      <p>Marco Marincola<br><i>Finance</i></p>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 text-center">
          <img class="img-responsive" style="margin:0 auto;" src="{{asset('images/giosetta.png')}}" alt="null" /><br>
          <p>Giosetta Ciuffa<br><i>External Relations</i></p>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 text-center">
      <img class="img-responsive" style="margin:0 auto;" src="{{asset('images/sara.png')}}" alt="null" /><br>
      <p>Sara Conallo<br><i>Jackie of all trades</i></p>
    </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 text-center">
      <img class="img-responsive" style="margin:0 auto;" src="{{asset('images/framba.png')}}" alt="null" /><br>
      <p>Federica Framba<br><i>Art Director</i></p>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 text-center">
      <img class="img-responsive" style="margin:0 auto;" src="{{asset('images/enea.png')}}" alt="null" /><br>
      <p>Enea Barbetta<br><i>Main Developer</i></p>
    </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 text-center">
      <img class="img-responsive" style="margin:0 auto;" src="{{asset('images/valentina.png')}}" alt="null" /><br>
     <p>Valentina Panizza<br><i>Strategic Planning</i></p>
    </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 text-center">
      <img class="img-responsive" style="margin:0 auto;" src="{{asset('images/stefania.png')}}" alt="null" /><br>
      <p>Stefania Forlani<br><i>Planning Updates</i></p>
    </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 text-center">
      <img class="img-responsive" style="margin:0 auto;" src="{{asset('images/francesco.png')}}" alt="null" /><br>
      <p>Francesco Taskayali<br><i>First Pianist</i></p>
    </div>
  </div>

  <!--<div class="row">
    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 text-center">
      <img class="img-responsive" style="margin:0 auto;" src="{{asset('images/giovanna.png')}}" alt="null" /><br>
      <p>Giovanna Littardi<br><i>First Guitarist</i></p>
    </div> -->

    </div>
  </div><br><br>

  <!--END CONTENT-->

  <!--BEGIN ROW-->
  <div class="row">

  <!--BEGIN LEFT COL-->
  <div class="col-md-2"></div>
  <!--END LEFT COL-->

  <!--BEGIN CONTENT-->
  <div class="col-md-8"><br>

  <p class="subheading transparency center space">FINANCE</p><br>
  <p class="base">We like so much transparency that we want everyone to be able to know our bank account balance and inspect our paypal account. We have nothing to hide.<br>
  <span class="transparency up">Bank account:</span> our IBAN is IT61D0623001623000043225634 - Filiale AG 23 Milano Cariparma di via della Moscova, and the current bank balance is around 200 euros, updated: 14 April 2018<br />
  <span class="transparency up">Paypal:</span> you can access our account from the standard paypal login with COOPERATION + password cooperation2016</p><br>

  <p class="subheading transparency center space">LEGAL STUFF</p><br>
  <p class="base">The Cooperacy Association was founded in Italy, Milan, the day 21/07/2015. Its current address is Via della Moscova 39, 20121 Milano.</p><br>

  <p id="contributors" name="contributors" style="color: #22DDEE; font-size: 24px; font-weight: bold; margin-bottom: 10px;">

  <p class="subheading transparency center space">CONTRIBUTORS LIST AND PLANNING</p><br>
  <p class="base">You can see in our <a class="ai" href="https://goo.gl/OYcrOS">planning</a> the list of names as well as the relative monetary value of the activity (including expenses) done as if monetary wages would have been corresponded to the participants. We keep track about it as we would correspond those amounts if we will have the possibility.<br><br>

  We're still doing some more work to allow better transparency. If you don't see something you're curious of, please <a class="ai" href="/contact">ask</a> for more information to be shown in this page.<br>
  Moreover, if you want, have a look at what could be <a class="ac" href="/aboutyou">your</a> interest in Cooperacy.</p>

  </div>
  <!--END CONTENT-->

  <!--BEGIN RIGHT COL-->
  <div class="col-md-2"></div>
  <!--END RIGHT COL-->

  </div>
  <!--END ROW-->

  <!--BEGIN SPACER-->
  <div class="row"><p style="height:20px;"></p></div>
  <!--END SPACER-->

</div>
<!--END CONTAINER-->


@stop
