@extends('layouts.lvapp')
@section('title')
    How it works - Cooperacy
@stop
@section('content')

<!--BEGIN CONTAINER-->
<div class="containerone">

  <!--BEGIN HEADER-->
  <div class="row">
  <br><img class="page-header" src="{{asset('/images/howitworks.png')}}"><br>
  </div>
  <!--END HEADER-->

  <!--BEGIN ROW-->
  <div class="row">

  <!--BEGIN LEFT COL-->
  <div class="col-md-2"></div>
  <!--END LEFT COL-->

  <!--BEGIN CONTENT-->
    <div class="col-md-8">
              <p class="subheading understanding center space margin">COOPERACY PLATFORM WHITE PAPER</p>
              <p class="base">This white paper explains how the Cooperacy platform works in detail.</p>
              <p class="subheading understanding center space margin">THE FUNDING ECOSYSTEM</p>
              <p class="base">Cooperacy <i>collection fund</i> is an amount of money generated by every member's one euro monthly subscription. One euro per month is 0.00000039 euros or 0.39 micro-euro per second:</p>

              <div class="row">
                <div class="col-lg-2 col-xs-12 base equivalence">Coomembers</div>
                <div class="col-lg-2 col-xs-12 base">&euro;/Second</div>
                <div class="col-lg-2 col-xs-12 base">Hour</div>
                <div class="col-lg-2 col-xs-12 base">Day</div>
                <div class="col-lg-2 col-xs-12 base">Month</div>
                <div class="col-lg-2 col-xs-12 base">Year</div>
              </div>
              <div class="row">
                <div class="col-lg-2 col-xs-12 base equivalence">1</div>
                <div class="col-lg-2 col-xs-12 base">0.39 micro</div>
                <div class="col-lg-2 col-xs-12 base">0.001</div>
                <div class="col-lg-2 col-xs-12 base">0.033</div>
                <div class="col-lg-2 col-xs-12 base">1</div>
                <div class="col-lg-2 col-xs-12 base">12</div>
              </div>
              <div class="row">
                <div class="col-lg-2 col-xs-12 base equivalence">100</div>
                <div class="col-lg-2 col-xs-12 base">0.000039</div>
                <div class="col-lg-2 col-xs-12 base">0.139</div>
                <div class="col-lg-2 col-xs-12 base">3.33</div>
                <div class="col-lg-2 col-xs-12 base">100</div>
                <div class="col-lg-2 col-xs-12 base">1200</div>
              </div>
              <div class="row">
                <div class="col-lg-2 col-xs-12 base equivalence">10k</div>
                <div class="col-lg-2 col-xs-12 base">0.0039</div>
                <div class="col-lg-2 col-xs-12 base">13.9</div>
                <div class="col-lg-2 col-xs-12 base">333</div>
                <div class="col-lg-2 col-xs-12 base">10k</div>
                <div class="col-lg-2 col-xs-12 base">120k</div>
              </div>
              <div class="row">
                <div class="col-lg-2 col-xs-12 base equivalence">1M</div>
                <div class="col-lg-2 col-xs-12 base">0.39</div>
                <div class="col-lg-2 col-xs-12 base">1389</div>
                <div class="col-lg-2 col-xs-12 base">33k</div>
                <div class="col-lg-2 col-xs-12 base">1M</div>
                <div class="col-lg-2 col-xs-12 base">12M</div>
              </div>
              <div class="row">
                <div class="col-lg-2 col-xs-12 base equivalence">1B</div>
                <div class="col-lg-2 col-xs-12 base">386</div>
                <div class="col-lg-2 col-xs-12 base">1389k</div>
                <div class="col-lg-2 col-xs-12 base">33M</div>
                <div class="col-lg-2 col-xs-12 base">1B</div>
                <div class="col-lg-2 col-xs-12 base">12B</div>
              </div>
              <div class="row">
                <div class="col-lg-2 col-xs-12 base equivalence">7B (World)</div>
                <div class="col-lg-2 col-xs-12 base">2700</div>
                <div class="col-lg-2 col-xs-12 base">9.7M</div>
                <div class="col-lg-2 col-xs-12 base">233M</div>
                <div class="col-lg-2 col-xs-12 base">7B</div>
                <div class="col-lg-2 col-xs-12 base">84B</div>
              </div>

              <p class="base">The money is allocated to the different ideas coming from the participants through their voting. Every second the microeuros are pre-allocated proportionally to the ideas: the more the votes, the more the proportional amount of microeuros. The money collected flows into the ideas until their budget is reached. When it happens, the ideas turn into "projects" starting the budget release phase.

              <p class="subheading understanding center space margin">MULTIDIMENSIONAL VOTING </p>
              <p class="base">In Cooperacy we don't vote for people, but for ideas. Both ideas and voting are anonymous until the ideas become projects. After that, all the information will be transparent for checking.<br> Anybody can vote for as many ideas they want. In order to leverage more collective intelligence, there are different kinds of votes:
              </p>

              <div class="row">
                <div class="col-lg-2 col-xs-12 base">VOTE</div>
                <div class="col-lg-10 col-xs-12 base">EFFECT</div>
              </div>
              <div class="row">
                <div class="col-lg-2 col-xs-12 base equivalence">Up</div>
                <div class="col-lg-10 col-xs-12 base">It determines the proportional allocation of funds. Principle: Equivalence. Technical: the proportions are calculated with the number of the Up (equivalence or orange) votes the budget idea has, divided by the total of all the Up votes all the ideas have (Vi / Vt ).</div>
              </div>
              <div class="row">
                <div class="col-lg-2 col-xs-12 base trust">Trust</div>
                <div class="col-lg-10 col-xs-12 base">Trust votes make the project skip the first budget milestone. It is a bit like to say “If this idea has a proof it can produce money, I support it in order to have a richer fund”. Principle: Trust. Technical: if trust votes are more than 75% of Up votes (TVi >75%Vi) first budget milestone is directly approved. Trust votes in a budget 0 idea indicate participation as Trustee, that is, as a client, affiliate, pre-buy, subscription to a course or pre-purchase to a concert. This vinculates the trustee to the payment of the relative pre-purchase or fee after the first milestone is passed.</div>
              </div>
              <div class="row">
                <div class="col-lg-2 col-xs-12 base care">Heartvote</div>
                <div class="col-lg-10 col-xs-12 base">It’s for sustainability projects or ones that generate emotional response in the voter. The emotional response in the future could also be generated thanks to biofeedback sensors. When heartvoted, the project gains higher visibility. Principle: Care. Technical: Ideas visibility is enhanced by heart votes percentages (HVi /HVt )</div>
              </div>
              <div class="row">
                <div class="col-lg-2 col-xs-12 base transparency">Joke</div>
                <div class="col-lg-10 col-xs-12 base">It’s a joke! This vote is a non-punishing way to determine spam. Joking votes include a description of why the project is a joke, and when joke-voted it is moved from the voting system to a final yearly joke-projects list, just for fun. Principle: Transparency. Technical: If joke votes, subtracted of half of the trust votes, are more than 25% of Up votes (JVt-50%*TVt > 25%*Vt ) the idea or project is blocked until the coordinators clarify. After 90 days of this blockage the budget is turned back to the collection fund. High Joke voted ideas go to a final year list in which the most Joke voted idea wins the prize of joke/trolling idea of the year.</div>
              </div>
              <div class="row">
                <div class="col-lg-2 col-xs-12 base freedom">Commitment</div>
                <div class="col-lg-10 col-xs-12 base">Commitment means you would like to work for the project. If the project needs human resources, it will choose you from the commitment list first. Principle: Freedom. Technical: Commitment blue votes fill in the requested hudget. People who Commit-voted an idea become participants when the idea turns into a project.</div>
              </div>
              <div class="row">
                <div class="col-lg-2 col-xs-12 base understanding">AI</div>
                <div class="col-lg-10 col-xs-12 base">This vote is given automatically by the AI and influences the participants with statistic motivations. Principle: Understanding</div>
              </div>
              <div class="row">
                <div class="col-lg-2 col-xs-12 base diversity">Bizarre</div>
                <div class="col-lg-10 col-xs-12 base">When a project has a strong “bizardry” (bizarre points), it has more opportunities to be randomly approved. Principle: Diversity. Technical: Every idea has a bizardry percentage, calculated by its bizardry votes over the total bizardry votes of the system (BVi / BVt ). Every idea, the first day of a season, is given a random percentage value between 0% and 10%, to which bizardry percentage is added. The idea that has the highest percentage has a virtual added Up votes percentage of +50% [(Vi+50%*Vt ) / Vt ]. Last minute high increments of bizarre votes will be turned into joke votes.</div>
              </div>



              <p class="base">The preallocation of the budget ideas is brought to 0 if there is no more activity on it by more than two users after 90 days, unless it has more than 50% of the budget, in that case the pre-allocated budget is kept safe.The preallocation of the budget idea is brought to 0 if the idea has a relative deadline, or a deadline connected with the hudget.
              Inner ecosystems budget ideas are intended to be voted and supported by their outer ecosystem’s internal budget. Budget ideas that want the Cooperacy collection fund distribution MUST be inner of Cooperacy main ecosystem to receive any budget pre-allocation, and then can be inserted as subproject of any inner ecosystem.
              Any direct donation to an idea counts as donated budget. Donated budget and pre-allocated budget count as per the fulfilment of the idea budget to be turned into a project, but donated budget cannot be returned to the collection fund unless the idea is rescinded or abandoned.
              Once the idea has reached the budget and/or hudget, the participants of the idea are kept frozen during the project phase until the project is turned into an ecosystem. The budget release to project has 7 milestones or steps. The milestones deadlines are chosen according to the Cooperacy governance scheme, starting from the coordinators.
              Eventual contrasts not resolved in the 7 milestones are solved voting, the voting is kept live for three days, in which the participants can change their votes, after which the voting is valid. The coordinators have three more days to try to creatively integrate the contrasting positions, during which the votes can only rise as positive supporting votes are frozen. At the end of a week time, the milestone has to be decided.
              All the contrasting votes not integrated reduce the budget, which goes back to the collection fund. In that case, the project turns back to the idea state, keeping the milestones approved, and waits again for the fulfilment of the missing budget cut due to contrasting positions.
              Current minimum budget for funded ideas is 1000 euros or equivalent.
              Voters (Up) of an idea become participants of that idea and of the future project/ecosystem. When the idea turns into a project, voters can leave the project and let it develop on its own. This is not considered an opposition.
              System registers full date of all votes
              Co-donation amount indicates the maximum amount you are willing to donate for the realization of the idea, that will be the same for all the co-donators. The system periodically evaluates the lowest of all amounts promised and multiplies for the number of the codonators in order to evaluate if the budget is reached. If not reached, the system evaluates other combination possibilities (all the amounts multiplied by the people who can afford more) able to reach the budget. Once turned into a project, the codonations are billed to your bank account, credit card or any other possibility the Site allows.
              City or Location projects are geographic units and are highlighted in blue. They can be default ecosystems that can have inner ones.
              Ideas can have other highlights like cyan for “educational”, violet for “scientific”, and green for “environmental” ones. You are free to use these labels, but if they are misleading they can make people Joke-vote them.
              When the project becomes an ecosystem it can receive a three level feedback (+,=,-)
              When an Idea becomes a project, the idea is “born”, and has a birthdate.
              In case of final transformation of an ecosystem, for example when a course ends, its final step is to go to a general archive. This step is called “death” and turns the ecosystem into a “memory”, where the AI analyzes it and the people may still give some feedback.
              Participants Gender (M / F / Other) will be in the future signal the modules composition.</p>


              <p class="subheading understanding center space margin">APPROVING A PROJECT</p>
              <p class="base">The approved idea from anonymous becomes transparent in its votes, proposers, and everything is shown. The pre-allocated fund is kept frozen for three days in which if people desire to change their support they can. If a percentage of the people decides not to support the idea anymore, that percentage is released back to the fund and goes to feed other projects. The project will receive the final amount of pre-allocation funding according to the new transparent voting percentage, without any more approval step at the end.<br>Projects lower than 1000 euros won’t be supported as according to crowdfunding sites statistics they averagely fail. Projects without activity or significant votes for a season (3 months) will release their pre-allocated funding and start over, in order to avoid fragmentation of the fund.</p>

              <p class="subheading understanding center space margin">BUDGET RELEASE</p>
              <p class="base">The budget release process is divided into 7 phases and every phase has a three days counter-voting time in which the process could be halted and the people in change changed for corruption or security reasons. Only people who upvoted, participated or are relative to the module will be notified of the phases. Participants are therefore allowed to counter-vote even if they are external to the module but only if they really care, as they won’t be notified otherwise. Every step is also voted for its transparency and sustainability.</p>
              <table>
                <tr>
                  <td> <strong>Phases</td>
                  <td> <strong>Given</td>
                  <td> <strong>Total</td>
                </tr>
                <tr>
                  <td><strong>Business plan</td>
                  <td>3%</td>
                  <td>3%</td>
                </tr>
                <tr>
                  <td><strong>Human Resources</td>
                  <td>10%</td>
                  <td>13%</td>
                </tr>
                <tr>
                  <td><strong>Setup</td>
                  <td>12%</td>
                  <td>25%</td>
                </tr>
                <tr>
                  <td><strong>Production</td>
                  <td>50%</td>
                  <td>75%</td>
                </tr>
                <tr>
                  <td><strong>Kick Off</td>
                  <td>12%</td>
                  <td>87%</td>
                </tr>
                <tr>
                  <td><strong>Fine Tuning</td>
                  <td>10%</td>
                  <td>97%</td>
                </tr>
                <tr>
                  <td><strong>Celebrate</td>
                  <td>3%</td>
                  <td>100%</td>
                </tr>
              </table>
              <p class="subheading understanding center space margin">AFTF</p>
              <p class="base">The voting process will be Anonymous First, Transparent Forever-after: the methodology we follow is similar to the Delphi Method. In our voting process, keeping it anonymous at the beginning makes any influence to be reduced. Turning it transparent afterwards and allowing people a 3-day rethinking time makes us grow and being mature in coping with truth, avoiding any kind of voting hacking, being the process verifiable. Anonymity allows to boost collective intelligence first, and transparency boosts cooperation afterwards. The information with this process is available to anybody, but it doesn't have a strong influential weight before the decision is made. This allows you to choose the project in which you want to work to or propose yours in full anonymity until the project reaches its desired hudget". After that, everything will always be public and 100% transparent also through the blockchain infrastructure. The legal framework will address the privacy issues.</p>

              <p class="subheading understanding center space margin">A REDISTRIBUTED COMMON POOL</p>
              <p class="base"> All projects are owned by COOPERACY, that is the Cooperacy participants’ fund. Corruption tends to disappear: once approved, projects are transparent and all the profits go back to the fund to give birth to new projects. Meanwhile, people earn good salaries because of the low taxation aspects of a not-for-profit or cooperative legal status. Salaries are monitored in a full transparency system: “equisalaries” will be a function of the platform that averages the wages that have similar amounts in order to keep standards of fairness, and specifies those that are way higher -or lower- than the average. Jobs that nobody wants to do or that require high skills may keep their higher salaries. Thanks to the “cooperative industry”, who works in a field can choose to work in the same field in another project, just like as it happens in the Mondragon Cooperative , a strong template we want to leverage from.</p>

              <p class="subheading understanding center space margin">THE COOPERACY PROJECTS AS MODULES</p>
              <p class="base">If the idea is a zero budget one, it will need just commitment by the people, that is, a hudget. Reached the hudget, the idea gets approved. As you see, there is a modular design in the projects. The modularity allows for an organic and circle-like approach that is able to create replicable open source blueprints for the whole platform community. Any project can have a parent and a child and be part of “circles” thanks to the tags. The biggest “parent” module is Cooperacy. Everyone will evaluate their happiness according to their preferences. A semantic engine will aggregate similar modules. <br>Every module has:<br>
              1. Information: every project has this visible information:</p>
              <p class="base">
                • Title (and proposers when anonymity ends) <br>
                • Representative image <br>
                • Subheading or objective of the project  <br>
                • Parents and children  <br>
                • Tags<br>
                • Location  <br>
                • Voting allowance (for specific local projects)<br></p>
              <p class="base">
              2. Coordinators: the ears of the module, they listen to what the participants want to do and execute it.<br>
              3. Participants: active hands of the module. Minimum 2, the coordinators, advised maximum 150.<br>
              4. Experts: possible special participants who do not vote but give advices. The “mouth” of the module.<br>
              5. Reporters: two “eyes” of the module, they write reports and compare the module with the business plan.<br>
              6. Hudget: the hudget required to fulfill the module: human commitment and budget.<br>
              7. Feed: the module is continuously subject of feedback by the participants and the voters. Even after years any participant can decide if something was good or bad, influencing the memory of the system. A simple feedback history is available: after 1 month (M), 1 season (S), 1 year (Y) and after 5 years (YY).<br>
              Feedback can be only of three kinds: HAPPY(+) MEDIUM(=) SAD(-)<br><br>
              The projects represent the voting unit of COOPERACY. They have this lifecycle:<br> </p>
              <p class="base">
                •	Idea: the idea or module is proposed – it is anonymous;<br>
                •	Vote: the idea or module is voted – anonymously;<br>
                •	Birth: the project is approved, anonymity ends;<br>
                •	Life: the budget is released according to the budget scheme;<br>
                •	Commitmenr: people needed are gathered or employed;<br>
                •	Death: when the mission is accomplished, the project “dies”. This is not a bitter end, it means the project goes in the archive. The project could also die due to economic loss and subsequent request to close the module after relative voting;<br>
                •	Memory: the module is archived and stored in the memory in order to influence future modules and for future reference;<br></p>
                <p class="subheading understanding center space margin">THE COOPERACY PROPORTIONAL GOVERNANCE</p>
                <p class="base">The COOPERACY governance is modular and proportional. Proportionality is a characteristic of the Equivalence condition in the COOPERACY model. Modularity is a derivate of the Understanding or Common Codes dimension, that establishes a common, fluid governance for all projects.<br>There are only two degrees of power, the “role” and the “participant” ones. Participants may assume a role, and have the leadership over a project. For example, if you have a project to sell special flowers, you have the role to manage the project. But if you just want to describe the project and let anybody who wants to accomplish it, then your role of manager will be held by someone else. Granularity will make the “special flowers” project made of subsections like accounting, cultivation etc. Every child project, like accounting, will have its roles.<br>“Roles” have the right to issue direct decisions over projects. Dual leadership is strongly advised: roles are usually two per module-project. When the roles issue direct decisions, these can be opposed by the module participants. They may even create special decisional projects called “budget 0” projects or modules.<br>Salaries are compared automatically with transparent collectively decided rules, so roles cannot impose them on participants and participants don’t need to wait centralized justice to act and change them. Participants are part of the governance, in every project. The power of every role is functional, not executive. That’s why roles “function”, but do not dominate, “request” but do not command. <br>If participants make an opposition, a voting is issued and its results are applied proportionally. To get an idea of the proportionality, this is pretty much like what you would do in a group of friends when you need to decide what to buy to have a dinner together. The majority want a dish, some others want some different meals, and you proportionally buy food coordinating the choices. Apparently this technique doesn’t seem to be applicable in some specific cases, but in our studies we found that those cases, when profoundly observed, are very, very limited.</p>

              <p class="subheading understanding center space margin">COOPERACY IS BASED ON HUMANS AND COMPUTERS</p>
              <p class="base">Cooperacy will analyze anything developed within itself. Due to its complete transparency, participants are owners and while they decide together they would contribute to a database which will allow Cooperacy to machine-learn continuously about the experiences of the ideas of the humans. The system will be probably based on an underlying public-blockchain structure with 100% transparency for transactions safety.<br />
                What does it mean? In simple words, Cooperacy will be based on a system that will compare all the ideas and, through the data we provide in those ideas, learn and give advice in order to make the ideas happen or warn when the ideas could fail.<br />
                This could seem a big controlling machine system, but there&#8217;s a trick: every human is allowed to communicate to the system their happiness, and the system will base its choices also on the most human, irrational and personal information of all: mood.<br />
                The data will be trasparent for every participant, and owned by everyone.<br />
                Powered by big data and human moods, the system will create an equilibrium of efficiency and humanity, and will behave like a single big organism or ecosystem.<br />
                In simplest words, the computers act as a &ldquo;memory&rdquo; of the system that every human can access in order to make better decisions.<br />
                All the profit goes back into the bank and can be only used to fund other ideas.</p>
  </div>
  <!--END CONTENT-->

  <!--BEGIN RIGHT COL-->
  <div class="col-md-2"></div>
  <!--END RIGHT COL-->

  </div>
  <!--END ROW-->

  <!--BEGIN SPACER-->
  <div class="row"><p style="height:20px;"></p></div>
  <!--END SPACER-->

</div>
<!--END CONTAINER-->
