@extends('layouts.lvapp')
@section('title')
    How it works - Cooperacy
@stop
@section('content')

<!--BEGIN CONTAINER-->
<div class="containerone">

  <!--BEGIN HEADER-->
  <div class="row">
  <br><img class="page-header" src="{{asset('/images/howitworks.png')}}"><br>
  </div>
  <!--END HEADER-->

  <!--BEGIN ROW-->
  <div class="row">

  <!--BEGIN LEFT COL-->
  <div class="col-md-2"></div>
  <!--END LEFT COL-->

  <!--BEGIN CONTENT-->
    <div class="col-md-8">
              <p class="base understanding">This white paper explains how the Cooperacy platform works in detail.</p>
              <p class="base">The platform is intended to develop the coomembers ideas. Cooperacy is the platform largest ecosystem, called Home. Any internal activity of Cooperacy is an ecosystem as well. Every ecosystem can be a part of other ones, or their home. All activities generated by the platform are co-owned by Cooperacy and its coomembers.</p>

              <p class="subheading understanding center space margin">THE COLLECTION FUND</p>
              <p class="base">Cooperacy <i>collection fund</i> is a collective amount of money generated by every member's one euro monthly subscription. One euro per month is 0.00000039 euros or 0.39 micro-euro per second:</p>

              <div class="row">
                <div class="col-lg-2 col-xs-12 base freedom">COOMEMBERS</div>
                <div class="col-lg-2 col-xs-12 base">&euro;/Second</div>
                <div class="col-lg-2 col-xs-12 base">Hour</div>
                <div class="col-lg-2 col-xs-12 base">Day</div>
                <div class="col-lg-2 col-xs-12 base">Month</div>
                <div class="col-lg-2 col-xs-12 base">Year</div>
              </div>
              <div class="row">
                <div class="col-lg-2 col-xs-12 base freedom">1</div>
                <div class="col-lg-2 col-xs-12 base">0.39 micro</div>
                <div class="col-lg-2 col-xs-12 base">0.001</div>
                <div class="col-lg-2 col-xs-12 base">0.033</div>
                <div class="col-lg-2 col-xs-12 base">1</div>
                <div class="col-lg-2 col-xs-12 base">12</div>
              </div>
              <div class="row">
                <div class="col-lg-2 col-xs-12 base freedom">100</div>
                <div class="col-lg-2 col-xs-12 base">0.000039</div>
                <div class="col-lg-2 col-xs-12 base">0.139</div>
                <div class="col-lg-2 col-xs-12 base">3.33</div>
                <div class="col-lg-2 col-xs-12 base">100</div>
                <div class="col-lg-2 col-xs-12 base">1200</div>
              </div>
              <div class="row">
                <div class="col-lg-2 col-xs-12 base freedom">10k</div>
                <div class="col-lg-2 col-xs-12 base">0.0039</div>
                <div class="col-lg-2 col-xs-12 base">13.9</div>
                <div class="col-lg-2 col-xs-12 base">333</div>
                <div class="col-lg-2 col-xs-12 base">10k</div>
                <div class="col-lg-2 col-xs-12 base">120k</div>
              </div>
              <div class="row">
                <div class="col-lg-2 col-xs-12 base freedom">1M</div>
                <div class="col-lg-2 col-xs-12 base">0.39</div>
                <div class="col-lg-2 col-xs-12 base">1389</div>
                <div class="col-lg-2 col-xs-12 base">33k</div>
                <div class="col-lg-2 col-xs-12 base">1M</div>
                <div class="col-lg-2 col-xs-12 base">12M</div>
              </div>
              <div class="row">
                <div class="col-lg-2 col-xs-12 base freedom">1B</div>
                <div class="col-lg-2 col-xs-12 base">386</div>
                <div class="col-lg-2 col-xs-12 base">1389k</div>
                <div class="col-lg-2 col-xs-12 base">33M</div>
                <div class="col-lg-2 col-xs-12 base">1B</div>
                <div class="col-lg-2 col-xs-12 base">12B</div>
              </div>
              <div class="row">
                <div class="col-lg-2 col-xs-12 base freedom">7B (World)</div>
                <div class="col-lg-2 col-xs-12 base">2700</div>
                <div class="col-lg-2 col-xs-12 base">9.7M</div>
                <div class="col-lg-2 col-xs-12 base">233M</div>
                <div class="col-lg-2 col-xs-12 base">7B</div>
                <div class="col-lg-2 col-xs-12 base">84B</div>
              </div>

              <p class="subheading understanding center space margin">IDEAS, PROJECTS, ECOSYSTEMS</p>
              <p class="base">The money is allocated to the different ideas coming from the participants through their voting. Every second the microeuros are pre-allocated proportionally to the ideas: the more the votes, the more the proportional amount of money. The collected funds are pre-allocated until the ideas budget is reached. When it happens, the idea turns into a "project" starting the budget release phase. After the project phase is completed, the idea becomes an "ecosystem". Ecosystem's profits go back to the collection fund.</p>

              <p class="subheading understanding center space margin">BUDGET 0 IDEAS</p>
              <p class="base">Ideas may need no budget. For example, they can be a tool for a decision making supported by voting. Some of them, instead, like courses, concerts, dinners, parties.. may not require a budget but a  minimum number of participants that commit themselves to the payment of a ticket or a fee, without which the ideas are not sustainable. All these ideas do not participate to the collection fund distribution, but their possible profit goes to the collection fund anyways, as all activities are co-owned by Cooperacy.</p>

              <p class="subheading understanding center space margin">AFTF MULTIDIMENSIONAL VOTING</p>
              <p class="base">In Cooperacy we don't vote for people, but for ideas. Both ideas and voting are anonymous until the ideas become projects. After that, all the information will be transparent for checking purposes. This is called AFTF, Anonymous First, Transparent Forever-after: the beginning anonymity allows to boost collective intelligence and transparency enhances cooperation afterwards. <br> Anybody can vote for as many ideas they want. In order to leverage more collective intelligence, there are different kinds of votes:
              </p><br>

              <div class="row">
                <div class="col-lg-2 col-xs-12 base">VOTE</div>
                <div class="col-lg-10 col-xs-12 base">EFFECT</div>
              </div>
              <div class="row">
                <div class="col-lg-2 col-xs-12 base equivalence">Up</div>
                <div class="col-lg-10 col-xs-12 base">It determines the proportional allocation of funds. Principle: Equivalence. Technical: the proportions are calculated with the number of the Up (equivalence or orange) votes the budget idea has, divided by the total of all the Up votes all the ideas have (Vi / Vt ). Upvoters become participants of the future projects.</div>
              </div>
              <div class="row">
                <div class="col-lg-2 col-xs-12 base trust">Trust</div>
                <div class="col-lg-10 col-xs-12 base">Trust votes make the project skip the first budget milestone. Principle: Trust. Technical: if trust votes are more than 75% of Up votes (TVi >75%Vi) the first budget milestone is directly approved. Trust votes in a "budget 0 idea" indicate participation as a Trustee, that is, as a client, affiliate, pre-buy, subscription to a course or pre-purchase to a concert. This vinculates the trustee to the payment of the relative pre-purchase or fee after the first milestone is passed.</div>
              </div>
              <div class="row">
                <div class="col-lg-2 col-xs-12 base care">Heartvote</div>
                <div class="col-lg-10 col-xs-12 base">It’s for sustainability projects or ones that generate emotional response in the voter. The emotional response in the future could also be generated thanks to biofeedback sensors. When heartvoted, the project gains higher visibility. Principle: Care. Technical: Ideas visibility is enhanced by heart votes percentages (HVi /HVt )</div>
              </div>
              <div class="row">
                <div class="col-lg-2 col-xs-12 base transparency">Crystal</div>
                <div class="col-lg-10 col-xs-12 base">This vote determines wether the idea is not hiding some information or cheating or spamming. Principle: Transparency. Technical: If the number of negative crystal votes, subtracted of half of the trust votes, are more than 25% of Up votes (JVt-50%*TVt > 25%*Vt ) the idea or project is blocked until the coordinators clarify. After 90 days of this blockage the budget is turned back to the collection fund.
                Negative crystal voters are not anonymous since the beginning. High Joke voted ideas go to a final year list in which the most Joke voted idea wins the prize of joke/trolling idea of the year.</div>
              </div>
              <div class="row">
                <div class="col-lg-2 col-xs-12 base freedom">Commitment</div>
                <div class="col-lg-10 col-xs-12 base">Commitment means you would like to work for the project. If the project needs human resources, it will choose you from the commitment list first. Principle: Freedom. Technical: Commitment blue votes fill in the requested hudget. People who Commit-voted an idea become participants when the idea turns into a project.</div>
              </div>
              <div class="row">
                <div class="col-lg-2 col-xs-12 base understanding">Understanding</div>
                <div class="col-lg-10 col-xs-12 base">This vote refers to how much the idea is comprehensible. It is an information for the idea proposer. The vote is also given an automatic amount by the Ecosystemic Learning artificial intelligence. This influences the participants with statistic motivations that include contextual information, fundamental to understand if the automated suggestion is helpful. Principle: Understanding</div>
              </div>
              <div class="row">
                <div class="col-lg-2 col-xs-12 base diversity">Bizarre</div>
                <div class="col-lg-10 col-xs-12 base">When a project has a strong “bizardry” (bizarre votes), it has more opportunities to be randomly approved. Principle: Diversity. Technical: Every idea has a bizardry percentage (BVi / BVt ). Every idea, the first day of a season, is given a random percentage value between 0% and 10%, to which bizardry percentage is added. The idea that has the highest percentage has a virtual added Up votes percentage of +50% [(Vi+50%*Vt ) / Vt ]. Last minute high increments of bizarre votes will be turned into joke votes.</div>
              </div>


              <p class="base">Current minimum budget for funded ideas is 1000 euros, as according to crowdfunding sites statistics ideas with lower amounts averagely fail.<br>
              Any direct donation to an idea counts as dedicated donated budget. Donated budget and pre-allocated budget count for the idea budget to be turned into a project, but donated budget cannot be returned to the collection fund unless the idea is rescinded or abandoned.<br>
              Once the idea has reached the budget and/or hudget, the participants of the idea are kept frozen during the project phase until the project is turned into an ecosystem. The budget release milestones deadlines are chosen according to the Cooperacy <a class="auf" href="/governance">governance</a> scheme.<br>
              Eventual contrasts not resolved in the 7 budget milestones are solved with a transparent voting kept live for three days, in which the participants can change their votes. The coordinators have three more days to try to creatively integrate the contrasting positions according to the seven solutions. At the end of a week time, the milestone should be decided.<br>
              All the contrasting votes not integrated reduce the budget, which goes back to the collection fund. In that case, the project turns back to the idea state, keeping the milestones approved, and waits again for the fulfilment of the missing budget cut due to contrasting positions.<br>
              Highlighting colors can indicate different ideas types, like cyan for “educational”, violet for “scientific”, and green for “environmental” ones. You are free to use these labels, but if they are misleading they can make people downvote them. Some ecosystems are geographic units, like cities or specific locations and are highlighted in blue.<br>
              When an Idea becomes a project, the idea is “born”, and has a birthdate. When the project becomes an ecosystem it can receive a three level feedback by the coomembers (+,=,-).<br>
              In case of “death” of an ecosystem, for example when a course ends, or a backery is sold, its final step is to be archived. This turns the ecosystem into a “memory" and the AI analyzes it while the participants may still give some feedback.<br>
              Participants Gender (M / F / Other) will be aggregated in order to inidicate in the future the modules (ideas, projects, ecosystems) gender composition.<br>
              Ecosystems may have internal ideas, for example a language institute that wants to add a new language course. Budget ideas that want to be funded by the Cooperacy collection fund must be in the Cooperacy Home ecosystem to receive any budget pre-allocation. Only afterwards they can be inserted as part of any ecosystem.<br>
            </p>

            <p class="subheading understanding center space margin">CO-DONATIONS</p>
            <p class="base">Co-donation is an alternative way in which you can help an idea to find its budget. When you hit on co-donate, you choose a maximum amount you are willing to donate for filling up the idea budget, if all the other co-donators are willing to donate the same. The system periodically evaluates the lowest of all amounts promised and multiplies for the number of the co-donators in order to see if the total budget is reached. If not, the system evaluates other combination possibilities able to reach the budget, like excluding lower donation amounts. Once a possible co-donation is found, the idea is turned into a project and the codonations are billed to your bank account, credit card or any other possibility the website allows.</p>

            <p class="subheading understanding center space margin">BUDGET RELEASE</p>
            <p class="base">The budget release process is divided into 7 phases and every phase has a three days approval voting time in which the process could be halted and the people in charge can be changed for corruption or security reasons. Only people who upvoted, participated or are relative to the module will be notified of the phases. Participants are therefore allowed to vote even if they are external to the module but only if they really care, as they won’t be notified otherwise. Every step is also voted for its transparency and sustainability.</p><br>

            <div class="row">
              <div class="col-lg-4 col-xs-12 base freedom">MILESTONES</div>
              <div class="col-lg-4 col-xs-12 base">% Released</div>
              <div class="col-lg-4 col-xs-12 base">% Incremental</div>
            </div>
            <div class="row">
              <div class="col-lg-4 col-xs-12 base freedom">Business Plan</div>
              <div class="col-lg-4 col-xs-12 base">3%</div>
              <div class="col-lg-4 col-xs-12 base">3%</div>
            </div>
            <div class="row">
              <div class="col-lg-4 col-xs-12 base freedom">Human Resources</div>
              <div class="col-lg-4 col-xs-12 base">10%</div>
              <div class="col-lg-4 col-xs-12 base">13%</div>
            </div>
            <div class="row">
              <div class="col-lg-4 col-xs-12 base freedom">Setup</div>
              <div class="col-lg-4 col-xs-12 base">12%</div>
              <div class="col-lg-4 col-xs-12 base">25%</div>
            </div>
            <div class="row">
              <div class="col-lg-4 col-xs-12 base freedom">Production</div>
              <div class="col-lg-4 col-xs-12 base">50%</div>
              <div class="col-lg-4 col-xs-12 base">75%</div>
            </div>
            <div class="row">
              <div class="col-lg-4 col-xs-12 base freedom">Kick Off</div>
              <div class="col-lg-4 col-xs-12 base">12%</div>
              <div class="col-lg-4 col-xs-12 base">87%</div>
            </div>
            <div class="row">
              <div class="col-lg-4 col-xs-12 base freedom">Fine Tuning</div>
              <div class="col-lg-4 col-xs-12 base">10%</div>
              <div class="col-lg-4 col-xs-12 base">97%</div>
            </div>
            <div class="row">
              <div class="col-lg-4 col-xs-12 base freedom">Celebrate</div>
              <div class="col-lg-4 col-xs-12 base">3%</div>
              <div class="col-lg-4 col-xs-12 base">100%</div>
            </div>

              <p class="subheading understanding center space margin">THE COOPERACY PROJECTS AS MODULES</p>
              <p class="base">As you see, there is a modular design in the projects. The modularity allows for an organic and circle-like approach that is able to create open source blueprints for the whole platform community. Any module (ideas, projects, ecosystems) can have a "home" and internal "parts".<br>
              Every module has:<br><br>
              1. Information set</p>
              <p class="base">
                • Title (and proposers when anonymity ends) <br>
                • Representative image <br>
                • Subheading or objective of the project<br>
                • Home and parts<br>
                • Tags<br>
                • Location<br>
                • Voting allowance (for specific local projects)<br></p>
              <p class="base">
              2. Coordinators: the ears of the module, they listen to what the participants want to do and execute it.<br>
              3. Participants: active hands of the module. Minimum 2, the coordinators, advised maximum 150.<br>
              4. Experts: possible special participants who do not vote but give advices. The “mouth” of the module.<br>
              5. Reporters: two “eyes” of the module, they write reports and compare the module with the business plan.<br>
              6. Hudget: the number of committed people required to realize the module.<br>
              7. Feed: the module is continuously subject of feedback by the participants and the voters. Even after years any participant can decide if something was good or bad, influencing the memory of the system. A simple feedback history is available: after 1 month (M), 1 season (S), 1 year (Y) and after 7 years (7).<br>
              Feedback can be only of three kinds: HAPPY(+) MEDIUM(=) SAD(-)<br><br>
              The projects represent the voting unit of Cooperacy. They have this lifecycle:<br> </p>
              <p class="base">
              •	Idea: the idea or module is proposed – it is anonymous;<br>
              •	Vote: the idea or module is voted – anonymously;<br>
              •	Birth: the idea becomes a project, anonymity ends, budget phase starts;<br>
              •	Life: the project becomes an ecosystem, its profits go back to the collection fund;<br>
              •	Death: when the mission is accomplished or terminated the project “dies”. This is not a bitter end, it means the project goes in the archive memory in order to influence future modules and for future reference;<br></p>
  </div>
  <!--END CONTENT-->

  <!--BEGIN RIGHT COL-->
  <div class="col-md-2"></div>
  <!--END RIGHT COL-->

  </div>
  <!--END ROW-->

  <!--BEGIN SPACER-->
  <div class="row"><p style="height:20px;"></p></div>
  <!--END SPACER-->

</div>
<!--END CONTAINER-->
