@extends('layouts.lvapp')
@section('title')
    Proportions - Cooperacy
@stop
@section('content')

<!--BEGIN CONTAINER-->
<div class="containerone">

  <!--BEGIN HEADER-->
  <div class="row">
    <br><img class="page-header" src="{{asset('/images/integration.png')}}">
  </div>
  <!--END HEADER-->

  <!--BEGIN ROW-->
  <div class="row">

  <!--BEGIN LEFT COL-->
  <div class="col-md-2"></div>
  <!--END LEFT COL-->

    <!--BEGIN CONTENT-->
    <div class="col-md-8">

    <br><p class="subheading diversity space center margin">LEARNING TO COOPERATE MEANS LEARNING TO INTEGRATE</p>
    <p class="base">Most conflictual situations are generated by different perspectives that polarize losing their <a class="aud" href="/cooperation#diversity">potential</a>.<br>A little amount of contrast is useful and even good sign, but when it turns into conflict, you experience direct or indirect, verbal or physical violence. In that case you tend to polarize, that is, to defend your position as you would if you were under a death menace. We found interesting <a class="aud" href="/solutions">solutions</a> to conflictual interactions, but you can generally use <i>proportional creativity integration</i> as a rule of thumb.</p>

    <p class="subheading understanding space center margin">CREATIVITY EVOLVES CONTRAST</p>
    <p class="base">Proportional creativity integration needs training as we're used to address situations with another different approach, the win/lose one, in which the winning position is the only one respected. In proportional creativity you first establish a criteria -that could be voting or weighting opportunities- to measure situations, and then try to creatively integrate the diverse perspectives. There is not a standard recipe (..for a <a class="auu" href="https://en.wikipedia.org/wiki/No_free_lunch_theorem">free lunch</a>): you need to know the context well. Let's see two examples.</p>

    <p class="subheading understanding space center margin">INTEGRATION NARRATIVES</p>

<!-- insert kitchen image here -->

    <p class="base">The first story is a simple one. In a company office, people want to use the kitchen zone for different purposes. Some want to use it as the standard lunch zone for the workers. Other people think cooking courses may be organized while some few other ones say they would use the colourful kitchen as an office. Three different views clashing one against another. Proportional space and time may solve the situation. The majority will use it as the lunch area, while the third group can use a proportional office space during working hours. Cooking workshops instead will be held in the weekend when nobody is working.</p>

    <p class="subheading understanding space center margin">CONTEXT</p>

<!-- insert ancient library image here -->

    <p class="base">Another famous example is that of a library in the summer, in which there's too much heat and a man wants to open a window, but a girl does not as that window is facing a restaurant: noise and various smells would fill the library and defocus the readers.<br><br>
    The two start to argue and conflict is near.. In this case proportional turns like opening the window one hour and then keeping it closed for another hour won't solve, as once the smells get into the library it won't easily go away. How would you solve this situation?<br><br>
    A brilliant librarian stopped the two, closed the window and.. opened another one on another room of the library, allowing fresh air to enter with no noise nor cooking smells. Simple, isn't it?<br>
    Once you know the context, creativity arises and <a class="aud" href="/solutions">solutions</a> are found in the integration of two opposite, clashing but right perspectives.</p>
    </div>
    <!--END CONTENT-->

    <!--BEGIN RIGHT COL-->
    <div class="col-md-2"></div>
    <!--END RIGHT COL-->

    </div>
    <!--END ROW-->

    <!--BEGIN SPACER-->
    <div class="row"><p style="height:20px;"></p></div>
    <!--END SPACER-->

</div>
<!--END CONTAINER-->

@stop
