@extends('layouts.lvapp')
@section('title')
    Proportions - Cooperacy
@stop
@section('content')

<!--BEGIN CONTAINER-->
<div class="containerone">

  <!--BEGIN SPACER-->
  <div class="row"><p style="height:30px;"></p></div>
  <!--END SPACER-->

  <!--BEGIN HEADER-->
  <div class="row">
    <br><img class="page-header" src="{{asset('/images/proportions.png')}}">
  </div>
  <!--END HEADER-->

  <!--BEGIN ROW-->
  <div class="row">

  <!--BEGIN LEFT COL-->
  <div class="col-md-2"></div>
  <!--END LEFT COL-->

    <!--BEGIN CONTENT-->
    <div class="col-md-8">

    <br><p class="subheading equivalence space center margin">LEARNING TO COOPERATE MEANS LEARNING TO INTEGRATE</p>
    <p class="base">Most conflictual situations are generated by different perspectives that polarize and lose their richness.<br>A little amount of contrast is useful and even good sign. When it turns into conflict you experience direct or indirect violence, and tend to polarize. We found some solutions to conflictual interactions, but you can generally use <i>proportional creativity</i> as a rule of thumb.</p>

    <p class="subheading equivalence space center margin">CREATIVITY EVOLVES CONTRAST</p>
    <p class="base">Proportional creativity needs training as we're used to address situations with another different approach, the win/lose one, in which the winning one is applied. In proportional creativity you first establish a criteria -that could be voting or weighting opportunities- to measure situations, and then try to creatively integrate the diverse perspectives. There is not a standard recipe (..for a free lunch): you need to know the context. Let's see two examples.</p>

    <p class="subheading equivalence space center margin">NARRATIVES OF PROPORTIONAL CREATIVITY</p>
    <p class="base">The first story is a simple one. In a company office, people want to use the kitchen zone for different purposes. Some want to use it as the standard lunch zone for the workers, others think cooking courses may be organized and some few other ones say they would use the colourful kitchen as an office. Proportional space -and time- solve the situation. The majority will use it as the lunch area, while people can use a proportional limited office space during working hours. Cooking workshops instead will be held in the weekend when nobody is working.</p>

    <p class="subheading equivalence space center margin">CONTEXT</p>
    <p class="base">Another famous example is the one of a library in the summer, in which there's too much heat and a man wants to open a window, but a girl does not as that window is facing a restaurant: noise and various smells would fill the library and defocus the readers.<br><br>
    The two start to argue and conflict is near.. Turns like opening the window one hour and then keeping it closed for another hour won't solve, as once the smells get into the library it won't easily go away. How would you solve this situation?<br><br>
    A brilliant librarian stopped the two, closed the window and.. opened another one on the opposite wall of the library, allowing fresh air to enter with no noise nor cooking smells. Simple, isn't it?<br>
    Once you know the context, creativity arises and solutions are found in the integration of two opposites, clashing, right perspectives.</p>
    </div>
    <!--END CONTENT-->

    <!--BEGIN RIGHT COL-->
    <div class="col-md-2"></div>
    <!--END RIGHT COL-->

    </div>
    <!--END ROW-->

    <!--BEGIN SPACER-->
    <div class="row"><p style="height:20px;"></p></div>
    <!--END SPACER-->

</div>
<!--END CONTAINER-->

@stop
